Modify some visual elements to make them look more coherent
shahednasser/quran-extension pull request #18
Opened 2021-11-06 09:55 UTC by murtuzaalisurti

Changed the following things:

1. The translation of the 'ayah' is now placed right under the arabic 'ayah' itself.
2. Gave title to the 'translation' and 'transliteration' of the Athkar. Redesigned it to look more coherent.
3. Did some minor UI changes.

2021-12-04 23:06 UTC, shahednasser requested changes
Hi @murtuzaalisurti thank you for your contribution and I'm sorry for taking long to check it out as I had a busy couple of weeks.

It all looks great! I just have a minor fixes below.

2021-12-04 23:06 UTC, shahednasser commented on css/styles.css
>    z-index: 10;
Can you remove this link as it now overlaps with the calendar when it opens

2021-12-04 23:06 UTC, shahednasser commented on js/main.js
> +  // });
You can remove these lines now

2021-12-05 13:58 UTC, murtuzaalisurti commented on css/styles.css
>    z-index: 10;
removed the z-index property

2021-12-05 13:58 UTC, murtuzaalisurti commented on js/main.js
> +  // });
done

2021-12-05 14:04 UTC, merged

2021-12-05 14:04 UTC, shahednasser commented
Great thanks! The changes will be a part of the next release