Add an option to show Arabic tafseer in Quran translation and fixed a minor bug
shahednasser/quran-extension pull request #21
Opened 2022-01-03 17:14 UTC by murtuzaalisurti

Successfully added an option which when selected, displays the tafseer in Arabic. Also, fixed a minor bug which wasn't displaying a translation language option correctly!

2022-01-03 17:50 UTC, shahednasser requested changes
Thank you @murtuzaalisurti for your work I just have a comment below

2022-01-03 17:50 UTC, shahednasser commented on js/main.js
> +                  else {
I think it isn't necessary to make a special case for Arabic language anymore, as it is now allowed to have translation.

However, we need to apply two styling properties on the `.translation-container .body` element when the translation is for Arabic:

```css
font-size: 17px;
direction: rtl;
```

You can do it in the `setTranslation` function by passing it the language as a second parameter. Then, you can place the above styles in a class (for example `.ar-translation`) and in `setTranslation` check if the language is `ar` then the class should be added to `.translation-container .body`.

If you also have a better approach then please go ahead.

2022-01-04 09:23 UTC, murtuzaalisurti commented on js/main.js
> +                  else {
did required changes! https://github.com/shahednasser/quran-extension/pull/21/commits/3371f1650cb8109e4c611452a54021de2dba9e40

2022-01-04 14:31 UTC, shahednasser commented on js/main.js
> +                  } else if(data.data[i].edition.type === "quran"){
Is this condition necessary?

2022-01-04 14:33 UTC, murtuzaalisurti commented on js/main.js
> +                  } else if(data.data[i].edition.type === "quran"){
the endpoint returns 3 objects, the first one is the verse, the second is for audio and the third one is for translation/tafsir.

2022-01-04 15:36 UTC, merged

2022-01-04 15:36 UTC, shahednasser commented
Great thank you so much!